name: Build Android 15 ROM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Create bin directory and install Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Set up authentication
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global credential.helper 'cache --timeout=3600'
          git config --global credential.username "andrealinux"
          git config --global credential.password "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"

      - name: Initialize Repo
        run: |
          mkdir -p ~/android
          cd ~/android
          ~/bin/repo init -u https://android.googlesource.com/platform/manifest -b android-15.0.0_r1
          ~/bin/repo sync

      - name: Build ROM
        run: |
          cd ~/android
          source build/envsetup.sh
          lunch aosp_vayu-userdebug
          make -j$(nproc)

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ROM
          path: ~/android/out/target/product/vayu/ROM.zip
